admin_login = "adminadmin"
admin_password = "adminuser"

host = "ep-falling-tree-ahxevp5u.c-3.us-east-1.aws.neon.tech"
database = "neondb"
user = "neondb_owner"
password = "npg_9Acyo4OkzFvE"
port = 5432
