services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    volumes:
      - ../backend:/app/backend
      - ../tests:/app/tests
      - ./insightface_models:/root/.insightface/models
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/src:/app/src
    restart: unless-stopped
