services:
  faceguard:
    image: ixkci/faceguard:latest
    ports:
      - "8501:8501"
    devices:
      - /dev/video0:/dev/video0
      # /dev/gpiomem is required for hardware LED access on Raspberry Pi
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ../backend/.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
      - ./insightface_models:/root/.insightface/models
    restart: unless-stopped
