services:
  faceguard:
    image: ixkci/faceguard:latest
    ports:
      - "8501:8501"
    environment:
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    devices:
      - /dev/video0:/dev/video0
      # /dev/gpiomem is required for hardware LED access on Raspberry Pi
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ../backend:/app/backend
      - ../tests:/app/tests
      - ./insightface_models:/root/.insightface/models
    restart: unless-stopped
