name: Deploy Documentation

on:
  push:
    branches:
      - main
      - 175-hosting-documentation

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-include-markdown-plugin

      - name: Build and Deploy
        run: mkdocs gh-deploy --force
